CONTRIBUTING.md
Updating CONTRIBUTING.md due to name change (Papillon => Renard)
=> Updating CONTRIBUTING.md due to name change

.github/workflows/build apk.yml
Please check if your PR fulfills the following requirements:
| Français `fr`                            |
| ---------------------------------------- |
| Proposez un changelog en français ici... |
Before merging this PR, you will need the approval of at least one of the following people:
- @ecnivtwelve
- @lucas-luchack
So be patient ;)
=> Update des documents sur Pawnote depuis main

.github/pull_request_template.md
Please check if your PR fulfills the following requirements:
| Français `fr`                            |
| ---------------------------------------- |
| Proposez un changelog en français ici... |
Before merging this PR, you will need the approval of at least one of the following people:
- @ecnivtwelve
- @lucas-luchack
So be patient ;)
=> Mise à jour de la template PR

views/Settings/AboutScreen.tsx, views/SettingsScreen.tsx
Corrections textuelles mineures (voir https://github.com/PapillonApp/Renard/pull/24)
=> Corrections textuelles mineures

package-lock.json
Reverts PapillonApp/Papillon#31
=> Revert "Bump ip from 1.1.8 to 1.1.9"

views/NewAuthStack/Pronote/NGPronoteLogin.tsx
[Ajout d'un bouton permettant d'afficher et de masquer le mot de passe sur l'écran de connexion Pronote]
=> Ajout d'un bouton pour afficher le mot de passe

views/Settings/AboutScreen.tsx
Changement du lien d'invitation Discord
=> Update du lien Discord

eas.json, metro.config.js, package-lock.json, package.json
Cette PR a pour seul but de rendre l'application *Papillon* compatible avec le wrapper API *scolengo-api* (wrapper non officiel).
:tada: Papillon devient compatible avec la librairie scolengo-api
La fusion de cette PR permet de développer sereinement l'intégration avec les ENT associés.
=> Compatibilité avec le wrapper scolengo-api

.github/ISSUE_TEMPLATE/bug.yaml
Update les versions et les placeholder pour plus de clarté lors de la déclaration d'un bug.
=> Mise à jour du template d'issue

fetch/BackgroundFetch.ts, fetch/background/BagReminder.ts, fetch/background/Helper.ts, fetch/background/SelfReminder.ts, views/Settings/NotificationsScreen.js, views/Settings/SettingsScreen.tsx
Lié à la suggestion du [Discord](https://discord.com/channels/1014931881906675712/1219606003641745478/1219606003641745478), j'ai ajouté 2 nouveau backgroundFetch, qui permettent d'être avertie entre 18h et 20h de faire son sac (si il y a des cours le lendemain), et une qui envoie une notification lorsque l'élève à cours dans la journée afin de lui rappeler de réserver son self. Les deux rappels sont désactivés par défaut ! Des réglages ont donc était ajouté au paramètrage des notifications.
FaceTime bug, le micro n'est pas lié à Papillon !
=> Ajouts des notifications de rappels (Faire son sac et réserver le self)

views/Grades/GradeView.tsx, views/GradesScreen.tsx, views/HomeScreen.tsx, views/Settings/CoursColor.js, views/Settings/SettingsScreen.tsx
Cette PR apporte l'ajout d'un menu dans l'onglet gestion des matières, afin de pouvoir y réinitialiser les couleurs par défaut des matières. L'action de "randomiser" les couleurs, ainsi que la réinitialisation son inclus dans un menu, et on chacun une confirmation avant d'appliquer les changement.
Elle contient également un petit bug fix concernant la page d'accueil ou la couleurs défini du cours n'était pas la bonne mais celle par défaut.
=> Ajout d'un bouton de réinitialisation des couleurs des cours

views/GradesScreen.tsx, views/Settings/SettingsScreen.tsx
Répare les fautes d'orthographe de la désactivation de l'onglet notes
=> fix: :pencil2: Fautes dans la désactivation des notes

views/Settings/TrophiesScreen.tsx
=> chore: :fire: Suppression temporaire des notifications de trophées

views/HomeScreen.tsx
Pour mettre un message, modifier ce fichier : https://github.com/PapillonApp/PapiRessources/blob/master/messages.json
=> feat: ajout d'un message de warning sur l'écran d'accueil en cas de besoin

stacks/AppStack.tsx, utils/UserReview.tsx
Popup qui invite a noter l'application à l'ouverture de l'app dans le but de recueillir plus d'avis sur les stores (App Store et Google Play)
> Pour éviter les abus **et que ça devienne chiant et intrusif**, il y a des **limitations**.
- **Pas plus d'une demande tous les 14 jours**
- L'application doit avoir été ouverte 8 fois avant chaque demande
- Passé les 14 jours, il faudra 8 nouvelles ouvertures pour réouvrir la popup
- Elle n'apparaît plus une fois acceptée
=> feat: :sparkles: Invitation à noter l'application sur les stores

views/Settings/TrophiesScreen.tsx
Répare l'apparence de l'écran des trophées sous Android
> NOTE : l'écran est inacessible dans la stack normale sans les nouveaux paramètres (https://github.com/PapillonApp/Papillon/pull/132)
=> fix: :lipstick: Apparence des trophées sous Android

views/Settings/NotificationsScreen.js, views/Settings/PaymentScreen.js, views/SettingsScreen.ios.tsx
Quelques corrections textuelles pour veillez à avoir une cohérence entre chaque menu.
=> Fix mineurs de typo

fetch/background/Lessons.ts
Ajout d'un texte spécifique à la notification du prochain cours si aucune salle n'est attribuer.
=> fix(notification): ajout d’un texte si aucune salle n'est attribuée

views/NewAuthStack/Pronote/FindEtab.tsx
J'ai ajouté un inset pour que ce soit comme sur les autres screen, voici le resultat :
| Avant | Après |
|--------|--------|
| <img src="https://github.com/PapillonApp/Papillon/assets/139133770/ec2cae58-d65f-404b-bba6-1712630095c7" width="200"> | <img src="https://github.com/PapillonApp/Papillon/assets/139133770/dd45b008-a45f-4948-a2a5-c72169ebde43" width="200"> |
J'ai ajouté un inset pour que ce soit comme sur les autres screen.
=> ui: Mini Mini PR, ajout d'un inset dans FindEtab.tsx

views/Grades/GradeView.tsx, views/GradesScreen.tsx
- Affichage détaillé des significants types
=> fix(grade): Affichage détaillé des significants types

views/Devoirs/HwScreen.tsx
Déposer la copie n'est pas encore supporté par Pawnote
en lien avec : https://github.com/PapillonApp/Papillon/issues/77
=> fix(homeworks): ajout d'un "soon" pour déposer ma copie

ios/PapillonWidget/Course/View/systemMediumCourseWidget.swift, ios/PapillonWidget/Grade/View/SystemMediumGradeWidget.swift, ios/PapillonWidget/Grade/View/SystemSmallGradeWidget.swift
fix(widget_ios): Affichage détaillé des significants types + EDT
**C'est du Swift et SwiftUI**
=> fix(widget_ios): Affichage détaillé des significants types + EDT

components/NativeItem.tsx, views/Cours/LessonScreen.tsx
Correction pour #152 
fix: Couleur des statuts LessonScreen
=> fix: Couleur des statuts LessonScreen

views/Settings/IconsScreen.js
J'ai ajouté le prénom en plus du prénom.
=> fix: changement nom auteur icône de la communauté

views/Settings/CoursColor.js
Affiche correctement le menu d'exportation des couleurs sous Android
=> fix: :bug: Menu export couleurs sous Android

utils/GetRessources/GetContribs/FormatContribs.ts
https://github.com/PapillonApp/Papillon/pull/166 celle ci sans conflits
=> fix(anael): suppression d'Anaël des manuals contribs

views/NewAuthStack/Pronote/FindEtab.tsx
Assombrir background en mode clair dans `FindEtab`
| Avant | Après |
|--------|--------|
| <img src="https://github.com/PapillonApp/Papillon/assets/139133770/3d51bdcf-e21b-494a-b154-627139a4be91" width="300"> | <img src="https://github.com/PapillonApp/Papillon/assets/139133770/a080f5ff-6c73-42bf-aba4-5caff1977ef9" width="300"> |
Assombrir background en mode clair dans `FindEtab`
=> Assombrir background en mode clair

stacks/AuthStack.tsx
=> fix: :ambulance: Fix de la connexion qui crash

android/app/src/main/res/values/strings.xml, android/settings.gradle, ios/Papillon.xcodeproj/project.pbxproj, ios/Papillon.xcodeproj/xcshareddata/xcschemes/Papillon.xcscheme, ios/Papillon.xcodeproj/xcshareddata/xcschemes/PapillonWidgetExtension.xcscheme, ios/Papillon/Info.plist
=> fix: :rocket: Paramètres de build iOS

fetch/background/Grades.ts
fix(widget_ios): Affichage détaillé des significants types coté RN
**C'est du Swift et SwiftUI**
=> fix(widget_ios): Affichage détaillé des significants types coté RN

views/CoursScreen.tsx
Fix de l'issue #74 + ajout d'un bouton pour rafraîchir manuellement l'EDT
=> Fixissue 74 (edt qui disparaît)

views/NewAuthStack/Pronote/NGPronoteLogin.tsx
Fix issue #116 : modification du message d'erreur en fonction de l'erreur retournée par Pawnote pour la connexion vanilla
Ajout de la désactivation du bouton si une tentative de connexion est en cours
=> Modification du message de l'erreur de connexion via la connexion vanilla (issue 116)

.github/ISSUE_TEMPLATE/bug.yaml, .github/pull_request_template.md
Actualisation du lien et corrections orthographiques
Actualisation du lien et corrections orthographiques
=> Modifications mineurs dans les guides de PRs

utils/cours/ColorCoursName.js, views/Settings/CoursColor.tsx
Fix de l'issue #178 (fix du reset des couleurs)
Modification du reset des couleurs :
- Option réinitialiser : restaure la couleur stockée en cache
- Option supprimer : permet de supprimer la couleur du cache et les récupérer de nouveau depuis le service scolaire
Les options sont aussi dispo dans le menu contextuel
=> Fix reset colors + ajout d'un cache des couleurs

package-lock.json, package.json
Pourquoi vous regardez ici ?
Ah vous voulez savoir ce que ça change ?
Ben ça fixe les bugs de reconnexion....
ça fixe aussi certains crashs
=> Upgrade pawnote to 0.21.0

fetch/index.ts, stacks/TabsStack.tsx, utils/cours/GetLessonStartTime.ts, utils/cours/GetNextCours.ts, views/HomeScreen.old.tsx, views/HomeScreen.tsx
Réécriture de l'écran d'accueil (sauf des widgets cours et devoirs qui ont été portés)
L'ancien écran d'accueil avait des nombreux problèmes qui ont été fixés ici :
- Animations et navigation lente ou non fonctionnelle
- Chargement lent, décalé ou non-parrallèle
- Affichage avec des composants dépréciés
- Ralentissements et bugs divers
- Performances et affichage sous Android
Les fonctions de détermination de prochain cours et de calcul du temps ont également été déplacées vers leurs utils.
**L'interface peut être amenée à changer a l'avenir, le but étant que ça soit stable principalement**
(l'enregistrement est full buggé mais c'est très fluide en pratique **même sous Android**)
https://github.com/PapillonApp/Papillon/assets/32978709/15dcc154-f452-4227-8f26-c137a27d2e6b
=> feat: :sparkles: Nouvel écran d'accueil

views/HomeScreen.tsx
=> fix: :dizzy: Animations élement prochain cours

views/HomeScreen.tsx
=> New course anim

views/HomeScreen.tsx
=> fix: :bug: Nom du prochain cours qui dépasse

views/NewAuthStack/EcoleDirecte/LoginEDForm.tsx
=> Amélioration du login EcoleDirecte

views/Cours/LessonScreen.tsx
=> fix(cours): rendering html description

views/Settings/CoursColor.tsx
=> beta 6.6.5 (avec fix d'un oubli)

views/NewAuthStack/Pronote/NGPronoteWebviewLogin.tsx
- Fix #207 : le message de connexion via la webview de connexion pronote spammait et rendait l'appli inutilisable sur certains ENT
- Ajout d'un message d'erreur si l'URL donnée dans la webview est invalide
=> Fix d'un spam de message de connexion via la webview de connexion + ajout message d'erreur si URL invalide

fetch/geolocation/geo-gouv.ts
Vérification de la validité de searchQuery dans geo-goouv.ts
Vérification de la validité de searchQuery dans geo-goouv.ts
=> Vérification de la validité de searchQuery dans geo-goouv.ts

package-lock.json, package.json, views/HomeScreen.tsx
- Fix de l'edt qui n'apparaissait pas dans l'accueil
- Maj de pawnote en version 0.21.1
=> Fix de l'edt qui n'apparaît pas dans l'accueil

views/HomeScreen.tsx
=> clean(homescreen): delete some useless console.log

views/HomeScreen.tsx
=> me tuez pas svp (j'ai encore oublié du nettoyage)

views/HomeScreen.tsx
- Fix d'un soucis qui rendait inaccessibles les paramètres de l'appli quand la photo de profil est désactivé sur pronote
--> à la place, un icone Paramètres s'affiche
=> fix d'un pb qui rendait inaccessibles les paramètres sans pp

views/News/NewsItem.tsx
- Fix : ajout des options de communication
=> Ajout des options des communications sur android

views/SchoolLifeScreen.tsx
- Feat : si plus de 3 évènements sont dans une même catégorie, seulement les 3 premiers seront affichés (possibilité de développer)
=> feat(schoolLife): ajout du tronquage automatique si plus de 3 évènements dans une même catégorie

stacks/AppStack.tsx, utils/cours/ColorCoursName.js, views/Devoirs/CreateHomeworkScreen.android.tsx, views/Devoirs/CreateHomeworkScreen.tsx, views/DevoirsScreen.tsx
- Fix : le local id n'était pas défini à cause d'une erreur de majuscule (`localId` au lieu de `localID`) sur les devoirs custom (#118) 
- Feat : ajout des devoirs custom sur android
=> Ajout des devoirs custom sur android + fix du local id non défini

views/Devoirs/CreateHomeworkScreen.android.tsx, views/Devoirs/CreateHomeworkScreen.tsx, views/Devoirs/HwScreen.tsx, views/DevoirsScreen.tsx
- Feat : ajout de l'édition d'un devoir custom (#171)
**Le test d'un dev iOS est souhaitable**, j'ai essayé d'intégrer la fonction dans la view ios sans pour autant pouvoir la tester
- Fix : ajout de la vérification d'un contenu de devoir vide (avec espaces seuls) sur android (déjà présent sur ios)
=> Ajout de l'édition d'un devoir custom

views/DevoirsScreen.tsx
Correction d'un manquement dans la PR #269 qui faisait qu'il n'y avait pas de multiline sur l'écran de devoir.
Pas besoin
=> feat (DevoirScreen): multiline for customHomework
